/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * TaskFlow API
 * OpenAPI spec version: 0.1.0
 */
import * as axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  ListTasksProjectsProjectIdTasksGetParams,
  TaskCreate,
  TaskResponse,
  TaskUpdate,
} from "../client.schemas";

/**
 * Create a new task in the project
 * @summary Create Task
 */
export const createTaskProjectsProjectIdTasksPost = <
  TData = AxiosResponse<TaskResponse>,
>(
  projectId: string,
  taskCreate: TaskCreate,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.post(
    `http://127.0.0.1:8000/projects/${projectId}/tasks`,
    taskCreate,
    options,
  );
};
/**
 * @summary List Tasks
 */
export const listTasksProjectsProjectIdTasksGet = <
  TData = AxiosResponse<TaskResponse[]>,
>(
  projectId: string,
  params?: ListTasksProjectsProjectIdTasksGetParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(
    `http://127.0.0.1:8000/projects/${projectId}/tasks`,
    {
      ...options,
      params: { ...params, ...options?.params },
    },
  );
};
/**
 * @summary Read Task
 */
export const readTaskTasksTaskIdGet = <TData = AxiosResponse<TaskResponse>>(
  taskId: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`http://127.0.0.1:8000/tasks/${taskId}`, options);
};
/**
 * @summary Update Task
 */
export const updateTaskTasksTaskIdPatch = <TData = AxiosResponse<TaskResponse>>(
  taskId: string,
  taskUpdate: TaskUpdate,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.patch(
    `http://127.0.0.1:8000/tasks/${taskId}`,
    taskUpdate,
    options,
  );
};
/**
 * @summary Delete Task
 */
export const deleteTaskTasksTaskIdDelete = <TData = AxiosResponse<void>>(
  taskId: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.delete(`http://127.0.0.1:8000/tasks/${taskId}`, options);
};
export type CreateTaskProjectsProjectIdTasksPostResult =
  AxiosResponse<TaskResponse>;
export type ListTasksProjectsProjectIdTasksGetResult = AxiosResponse<
  TaskResponse[]
>;
export type ReadTaskTasksTaskIdGetResult = AxiosResponse<TaskResponse>;
export type UpdateTaskTasksTaskIdPatchResult = AxiosResponse<TaskResponse>;
export type DeleteTaskTasksTaskIdDeleteResult = AxiosResponse<void>;
