/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * TaskFlow API
 * OpenAPI spec version: 0.1.0
 */
import * as axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  UserResponse,
  UserStatusUpdate,
  UserUpdate,
} from "../client.schemas";

/**
 * @summary Read User Me
 */
export const readUserMeUsersMeGet = <TData = AxiosResponse<UserResponse>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`http://127.0.0.1:8000/users/me`, options);
};
/**
 * @summary Update User Me
 */
export const updateUserMeUsersMePatch = <TData = AxiosResponse<UserResponse>>(
  userUpdate: UserUpdate,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.patch(
    `http://127.0.0.1:8000/users/me`,
    userUpdate,
    options,
  );
};
/**
 * @summary Read User By Id
 */
export const readUserByIdUsersUserIdGet = <TData = AxiosResponse<UserResponse>>(
  userId: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`http://127.0.0.1:8000/users/${userId}`, options);
};
/**
 * @summary Update User Status
 */
export const updateUserStatusUsersUserIdStatusPatch = <
  TData = AxiosResponse<UserResponse>,
>(
  userId: string,
  userStatusUpdate: UserStatusUpdate,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.patch(
    `http://127.0.0.1:8000/users/${userId}/status`,
    userStatusUpdate,
    options,
  );
};
export type ReadUserMeUsersMeGetResult = AxiosResponse<UserResponse>;
export type UpdateUserMeUsersMePatchResult = AxiosResponse<UserResponse>;
export type ReadUserByIdUsersUserIdGetResult = AxiosResponse<UserResponse>;
export type UpdateUserStatusUsersUserIdStatusPatchResult =
  AxiosResponse<UserResponse>;
