/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * TaskFlow API
 * OpenAPI spec version: 0.1.0
 */
import * as axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type { UserCreate, UserLogin, UserResponse } from "../client.schemas";

/**
 * Register a new user controller
 * @summary Register
 */
export const registerAuthRegisterPost = <TData = AxiosResponse<UserResponse>>(
  userCreate: UserCreate,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.post(
    `http://127.0.0.1:8000/auth/register`,
    userCreate,
    options,
  );
};
/**
 * Login a user controller
 * @summary Login
 */
export const loginAuthLoginPost = <TData = AxiosResponse<UserResponse>>(
  userLogin: UserLogin,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.post(
    `http://127.0.0.1:8000/auth/login`,
    userLogin,
    options,
  );
};
/**
 * Refresh a user the access token
 * @summary Refresh Token Endpoint
 */
export const refreshTokenEndpointAuthRefreshPost = <
  TData = AxiosResponse<UserResponse>,
>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.post(
    `http://127.0.0.1:8000/auth/refresh`,
    undefined,
    options,
  );
};
/**
 * @summary Logout
 */
export const logoutAuthLogoutPost = <TData = AxiosResponse<unknown>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.post(
    `http://127.0.0.1:8000/auth/logout`,
    undefined,
    options,
  );
};
/**
 * @summary Read Users Me
 */
export const readUsersMeAuthMeGet = <TData = AxiosResponse<UserResponse>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`http://127.0.0.1:8000/auth/me`, options);
};
export type RegisterAuthRegisterPostResult = AxiosResponse<UserResponse>;
export type LoginAuthLoginPostResult = AxiosResponse<UserResponse>;
export type RefreshTokenEndpointAuthRefreshPostResult =
  AxiosResponse<UserResponse>;
export type LogoutAuthLogoutPostResult = AxiosResponse<unknown>;
export type ReadUsersMeAuthMeGetResult = AxiosResponse<UserResponse>;
