/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * TaskFlow API
 * OpenAPI spec version: 0.1.0
 */
export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type ProjectCreateDescription = string | null;

export interface ProjectCreate {
  name: string;
  description?: ProjectCreateDescription;
}

export interface ProjectMemberCreate {
  user_id: string;
  role?: Role;
}

export interface ProjectMemberResponse {
  id: string;
  user_id: string;
  project_id: string;
  role: Role;
  created_at: string;
}

export interface ProjectMemberUpdate {
  role: Role;
}

export type ProjectPriority =
  (typeof ProjectPriority)[keyof typeof ProjectPriority];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectPriority = {
  low: "low",
  medium: "medium",
  high: "high",
} as const;

export type ProjectResponseDescription = string | null;

export interface ProjectResponse {
  id: string;
  name: string;
  description?: ProjectResponseDescription;
  owner_id: string;
  created_at: string;
  updated_at: string;
}

export type ProjectStatus = (typeof ProjectStatus)[keyof typeof ProjectStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectStatus = {
  todo: "todo",
  in_progress: "in_progress",
  done: "done",
} as const;

export type ProjectUpdateName = string | null;

export type ProjectUpdateDescription = string | null;

export interface ProjectUpdate {
  name?: ProjectUpdateName;
  description?: ProjectUpdateDescription;
}

export type Role = (typeof Role)[keyof typeof Role];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Role = {
  admin: "admin",
  user: "user",
} as const;

export type TaskCreateDescription = string | null;

export type TaskCreateAssignedTo = string | null;

export type TaskCreateDueDatetime = string | null;

export interface TaskCreate {
  title: string;
  description?: TaskCreateDescription;
  status?: ProjectStatus;
  priority?: ProjectPriority;
  assigned_to?: TaskCreateAssignedTo;
  due_datetime?: TaskCreateDueDatetime;
}

export type TaskResponseDescription = string | null;

export type TaskResponseAssignedTo = string | null;

export type TaskResponseDueDatetime = string | null;

export interface TaskResponse {
  id: string;
  project_id: string;
  title: string;
  description?: TaskResponseDescription;
  status: ProjectStatus;
  priority: ProjectPriority;
  assigned_to?: TaskResponseAssignedTo;
  created_by: string;
  due_datetime?: TaskResponseDueDatetime;
  created_at: string;
  updated_at: string;
}

export type TaskUpdateTitle = string | null;

export type TaskUpdateDescription = string | null;

export type TaskUpdateStatus = ProjectStatus | null;

export type TaskUpdatePriority = ProjectPriority | null;

export type TaskUpdateAssignedTo = string | null;

export type TaskUpdateDueDatetime = string | null;

export interface TaskUpdate {
  title?: TaskUpdateTitle;
  description?: TaskUpdateDescription;
  status?: TaskUpdateStatus;
  priority?: TaskUpdatePriority;
  assigned_to?: TaskUpdateAssignedTo;
  due_datetime?: TaskUpdateDueDatetime;
}

export interface UserCreate {
  email: string;
  password: string;
  full_name: string;
}

export interface UserLogin {
  email: string;
  password: string;
}

export interface UserResponse {
  id: string;
  email: string;
  full_name: string;
  role: Role;
  is_active: boolean;
}

export interface UserStatusUpdate {
  is_active: boolean;
}

export type UserUpdateFullName = string | null;

export interface UserUpdate {
  full_name?: UserUpdateFullName;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type ListTasksProjectsProjectIdTasksGetParams = {
  status?: ProjectStatus | null;
  priority?: ProjectPriority | null;
  /**
   * @minimum 1
   */
  page?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};
