/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * TaskFlow API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Register a new user controller
 * @summary Register
 */
export const registerAuthRegisterPostBody = zod.object({
  email: zod.email(),
  password: zod.string(),
  full_name: zod.string(),
});

export const registerAuthRegisterPostResponse = zod.object({
  id: zod.uuid(),
  email: zod.email(),
  full_name: zod.string(),
  role: zod.enum(["admin", "user"]),
  is_active: zod.boolean(),
});

/**
 * Login a user controller
 * @summary Login
 */
export const loginAuthLoginPostBody = zod.object({
  email: zod.email(),
  password: zod.string(),
});

export const loginAuthLoginPostResponse = zod.object({
  id: zod.uuid(),
  email: zod.email(),
  full_name: zod.string(),
  role: zod.enum(["admin", "user"]),
  is_active: zod.boolean(),
});

/**
 * Refresh a user the access token
 * @summary Refresh Token Endpoint
 */
export const refreshTokenEndpointAuthRefreshPostResponse = zod.object({
  id: zod.uuid(),
  email: zod.email(),
  full_name: zod.string(),
  role: zod.enum(["admin", "user"]),
  is_active: zod.boolean(),
});

/**
 * @summary Logout
 */
export const logoutAuthLogoutPostResponse = zod.unknown();

/**
 * @summary Read Users Me
 */
export const readUsersMeAuthMeGetResponse = zod.object({
  id: zod.uuid(),
  email: zod.email(),
  full_name: zod.string(),
  role: zod.enum(["admin", "user"]),
  is_active: zod.boolean(),
});

/**
 * @summary Read User Me
 */
export const readUserMeUsersMeGetResponse = zod.object({
  id: zod.uuid(),
  email: zod.email(),
  full_name: zod.string(),
  role: zod.enum(["admin", "user"]),
  is_active: zod.boolean(),
});

/**
 * @summary Update User Me
 */
export const updateUserMeUsersMePatchBody = zod.object({
  full_name: zod.union([zod.string(), zod.null()]).optional(),
});

export const updateUserMeUsersMePatchResponse = zod.object({
  id: zod.uuid(),
  email: zod.email(),
  full_name: zod.string(),
  role: zod.enum(["admin", "user"]),
  is_active: zod.boolean(),
});

/**
 * @summary Read User By Id
 */
export const readUserByIdUsersUserIdGetParams = zod.object({
  user_id: zod.string(),
});

export const readUserByIdUsersUserIdGetResponse = zod.object({
  id: zod.uuid(),
  email: zod.email(),
  full_name: zod.string(),
  role: zod.enum(["admin", "user"]),
  is_active: zod.boolean(),
});

/**
 * @summary Update User Status
 */
export const updateUserStatusUsersUserIdStatusPatchParams = zod.object({
  user_id: zod.string(),
});

export const updateUserStatusUsersUserIdStatusPatchBody = zod.object({
  is_active: zod.boolean(),
});

export const updateUserStatusUsersUserIdStatusPatchResponse = zod.object({
  id: zod.uuid(),
  email: zod.email(),
  full_name: zod.string(),
  role: zod.enum(["admin", "user"]),
  is_active: zod.boolean(),
});

/**
 * List all projects for the current user
 * @summary List Projects
 */
export const listProjectsProjectsGetResponseItem = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  description: zod.union([zod.string(), zod.null()]).optional(),
  owner_id: zod.uuid(),
  created_at: zod.iso.datetime({}),
  updated_at: zod.iso.datetime({}),
});
export const listProjectsProjectsGetResponse = zod.array(
  listProjectsProjectsGetResponseItem,
);

/**
 * Create a new project
 * @summary Create Project
 */
export const createProjectProjectsPostBody = zod.object({
  name: zod.string(),
  description: zod.union([zod.string(), zod.null()]).optional(),
});

/**
 * @summary Read Project
 */
export const readProjectProjectsProjectIdGetParams = zod.object({
  project_id: zod.uuid(),
});

export const readProjectProjectsProjectIdGetResponse = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  description: zod.union([zod.string(), zod.null()]).optional(),
  owner_id: zod.uuid(),
  created_at: zod.iso.datetime({}),
  updated_at: zod.iso.datetime({}),
});

/**
 * @summary Update Project
 */
export const updateProjectProjectsProjectIdPatchParams = zod.object({
  project_id: zod.uuid(),
});

export const updateProjectProjectsProjectIdPatchBody = zod.object({
  name: zod.union([zod.string(), zod.null()]).optional(),
  description: zod.union([zod.string(), zod.null()]).optional(),
});

export const updateProjectProjectsProjectIdPatchResponse = zod.object({
  id: zod.uuid(),
  name: zod.string(),
  description: zod.union([zod.string(), zod.null()]).optional(),
  owner_id: zod.uuid(),
  created_at: zod.iso.datetime({}),
  updated_at: zod.iso.datetime({}),
});

/**
 * @summary Delete Project
 */
export const deleteProjectProjectsProjectIdDeleteParams = zod.object({
  project_id: zod.uuid(),
});

/**
 * Add a new member to the project
 * @summary Add Project Member Endpoint
 */
export const addProjectMemberEndpointProjectsProjectIdMembersPostParams =
  zod.object({
    project_id: zod.uuid(),
  });

export const addProjectMemberEndpointProjectsProjectIdMembersPostBody =
  zod.object({
    user_id: zod.uuid(),
    role: zod.enum(["admin", "user"]).optional(),
  });

export const addProjectMemberEndpointProjectsProjectIdMembersPostResponse =
  zod.object({
    id: zod.uuid(),
    user_id: zod.uuid(),
    project_id: zod.uuid(),
    role: zod.enum(["admin", "user"]),
    created_at: zod.iso.datetime({}),
  });

/**
 * List all members of the project
 * @summary List Project Members
 */
export const listProjectMembersProjectsProjectIdMembersGetParams = zod.object({
  project_id: zod.uuid(),
});

export const listProjectMembersProjectsProjectIdMembersGetResponseItem =
  zod.object({
    id: zod.uuid(),
    user_id: zod.uuid(),
    project_id: zod.uuid(),
    role: zod.enum(["admin", "user"]),
    created_at: zod.iso.datetime({}),
  });
export const listProjectMembersProjectsProjectIdMembersGetResponse = zod.array(
  listProjectMembersProjectsProjectIdMembersGetResponseItem,
);

/**
 * Update the project member role
 * @summary Update Project Member Role
 */
export const updateProjectMemberRoleProjectsProjectIdMembersUserIdPatchParams =
  zod.object({
    project_id: zod.uuid(),
    user_id: zod.uuid(),
  });

export const updateProjectMemberRoleProjectsProjectIdMembersUserIdPatchBody =
  zod.object({
    role: zod.enum(["admin", "user"]),
  });

export const updateProjectMemberRoleProjectsProjectIdMembersUserIdPatchResponse =
  zod.object({
    id: zod.uuid(),
    user_id: zod.uuid(),
    project_id: zod.uuid(),
    role: zod.enum(["admin", "user"]),
    created_at: zod.iso.datetime({}),
  });

/**
 * Remove the project member from the project
 * @summary Remove Project Member
 */
export const removeProjectMemberProjectsProjectIdMembersUserIdDeleteParams =
  zod.object({
    project_id: zod.uuid(),
    user_id: zod.uuid(),
  });

/**
 * Create a new task in the project
 * @summary Create Task
 */
export const createTaskProjectsProjectIdTasksPostParams = zod.object({
  project_id: zod.uuid(),
});

export const createTaskProjectsProjectIdTasksPostBody = zod.object({
  title: zod.string(),
  description: zod.union([zod.string(), zod.null()]).optional(),
  status: zod.enum(["todo", "in_progress", "done"]).optional(),
  priority: zod.enum(["low", "medium", "high"]).optional(),
  assigned_to: zod.union([zod.uuid(), zod.null()]).optional(),
  due_datetime: zod.union([zod.iso.datetime({}), zod.null()]).optional(),
});

/**
 * @summary List Tasks
 */
export const listTasksProjectsProjectIdTasksGetParams = zod.object({
  project_id: zod.uuid(),
});

export const listTasksProjectsProjectIdTasksGetQueryPageDefault = 1;

export const listTasksProjectsProjectIdTasksGetQueryLimitDefault = 10;
export const listTasksProjectsProjectIdTasksGetQueryLimitMax = 100;

export const listTasksProjectsProjectIdTasksGetQueryParams = zod.object({
  status: zod
    .union([zod.enum(["todo", "in_progress", "done"]), zod.null()])
    .optional(),
  priority: zod
    .union([zod.enum(["low", "medium", "high"]), zod.null()])
    .optional(),
  page: zod
    .number()
    .min(1)
    .default(listTasksProjectsProjectIdTasksGetQueryPageDefault),
  limit: zod
    .number()
    .min(1)
    .max(listTasksProjectsProjectIdTasksGetQueryLimitMax)
    .default(listTasksProjectsProjectIdTasksGetQueryLimitDefault),
});

export const listTasksProjectsProjectIdTasksGetResponseItem = zod.object({
  id: zod.uuid(),
  project_id: zod.uuid(),
  title: zod.string(),
  description: zod.union([zod.string(), zod.null()]).optional(),
  status: zod.enum(["todo", "in_progress", "done"]),
  priority: zod.enum(["low", "medium", "high"]),
  assigned_to: zod.union([zod.uuid(), zod.null()]).optional(),
  created_by: zod.uuid(),
  due_datetime: zod.union([zod.iso.datetime({}), zod.null()]).optional(),
  created_at: zod.iso.datetime({}),
  updated_at: zod.iso.datetime({}),
});
export const listTasksProjectsProjectIdTasksGetResponse = zod.array(
  listTasksProjectsProjectIdTasksGetResponseItem,
);

/**
 * @summary Read Task
 */
export const readTaskTasksTaskIdGetParams = zod.object({
  task_id: zod.uuid(),
});

export const readTaskTasksTaskIdGetResponse = zod.object({
  id: zod.uuid(),
  project_id: zod.uuid(),
  title: zod.string(),
  description: zod.union([zod.string(), zod.null()]).optional(),
  status: zod.enum(["todo", "in_progress", "done"]),
  priority: zod.enum(["low", "medium", "high"]),
  assigned_to: zod.union([zod.uuid(), zod.null()]).optional(),
  created_by: zod.uuid(),
  due_datetime: zod.union([zod.iso.datetime({}), zod.null()]).optional(),
  created_at: zod.iso.datetime({}),
  updated_at: zod.iso.datetime({}),
});

/**
 * @summary Update Task
 */
export const updateTaskTasksTaskIdPatchParams = zod.object({
  task_id: zod.uuid(),
});

export const updateTaskTasksTaskIdPatchBody = zod.object({
  title: zod.union([zod.string(), zod.null()]).optional(),
  description: zod.union([zod.string(), zod.null()]).optional(),
  status: zod
    .union([zod.enum(["todo", "in_progress", "done"]), zod.null()])
    .optional(),
  priority: zod
    .union([zod.enum(["low", "medium", "high"]), zod.null()])
    .optional(),
  assigned_to: zod.union([zod.uuid(), zod.null()]).optional(),
  due_datetime: zod.union([zod.iso.datetime({}), zod.null()]).optional(),
});

export const updateTaskTasksTaskIdPatchResponse = zod.object({
  id: zod.uuid(),
  project_id: zod.uuid(),
  title: zod.string(),
  description: zod.union([zod.string(), zod.null()]).optional(),
  status: zod.enum(["todo", "in_progress", "done"]),
  priority: zod.enum(["low", "medium", "high"]),
  assigned_to: zod.union([zod.uuid(), zod.null()]).optional(),
  created_by: zod.uuid(),
  due_datetime: zod.union([zod.iso.datetime({}), zod.null()]).optional(),
  created_at: zod.iso.datetime({}),
  updated_at: zod.iso.datetime({}),
});

/**
 * @summary Delete Task
 */
export const deleteTaskTasksTaskIdDeleteParams = zod.object({
  task_id: zod.uuid(),
});
