"""create users table

Revision ID: b5835a2c587f
Revises: 
Create Date: 2026-07-30 15:12:30.505504

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'b5835a2c587f'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
