/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * TaskFlow API
 * OpenAPI spec version: 0.1.0
 */
import * as axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  ProjectCreate,
  ProjectMemberCreate,
  ProjectMemberResponse,
  ProjectMemberUpdate,
  ProjectResponse,
  ProjectUpdate,
} from "../client.schemas";

/**
 * List all projects for the current user
 * @summary List Projects
 */
export const listProjectsProjectsGet = <
  TData = AxiosResponse<ProjectResponse[]>,
>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`http://127.0.0.1:8000/projects/`, options);
};
/**
 * Create a new project
 * @summary Create Project
 */
export const createProjectProjectsPost = <
  TData = AxiosResponse<ProjectResponse>,
>(
  projectCreate: ProjectCreate,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.post(
    `http://127.0.0.1:8000/projects/`,
    projectCreate,
    options,
  );
};
/**
 * @summary Read Project
 */
export const readProjectProjectsProjectIdGet = <
  TData = AxiosResponse<ProjectResponse>,
>(
  projectId: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(
    `http://127.0.0.1:8000/projects/${projectId}`,
    options,
  );
};
/**
 * @summary Update Project
 */
export const updateProjectProjectsProjectIdPatch = <
  TData = AxiosResponse<ProjectResponse>,
>(
  projectId: string,
  projectUpdate: ProjectUpdate,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.patch(
    `http://127.0.0.1:8000/projects/${projectId}`,
    projectUpdate,
    options,
  );
};
/**
 * @summary Delete Project
 */
export const deleteProjectProjectsProjectIdDelete = <
  TData = AxiosResponse<void>,
>(
  projectId: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.delete(
    `http://127.0.0.1:8000/projects/${projectId}`,
    options,
  );
};
/**
 * Add a new member to the project
 * @summary Add Project Member Endpoint
 */
export const addProjectMemberEndpointProjectsProjectIdMembersPost = <
  TData = AxiosResponse<ProjectMemberResponse>,
>(
  projectId: string,
  projectMemberCreate: ProjectMemberCreate,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.post(
    `http://127.0.0.1:8000/projects/${projectId}/members`,
    projectMemberCreate,
    options,
  );
};
/**
 * List all members of the project
 * @summary List Project Members
 */
export const listProjectMembersProjectsProjectIdMembersGet = <
  TData = AxiosResponse<ProjectMemberResponse[]>,
>(
  projectId: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(
    `http://127.0.0.1:8000/projects/${projectId}/members`,
    options,
  );
};
/**
 * Update the project member role
 * @summary Update Project Member Role
 */
export const updateProjectMemberRoleProjectsProjectIdMembersUserIdPatch = <
  TData = AxiosResponse<ProjectMemberResponse>,
>(
  projectId: string,
  userId: string,
  projectMemberUpdate: ProjectMemberUpdate,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.patch(
    `http://127.0.0.1:8000/projects/${projectId}/members/${userId}`,
    projectMemberUpdate,
    options,
  );
};
/**
 * Remove the project member from the project
 * @summary Remove Project Member
 */
export const removeProjectMemberProjectsProjectIdMembersUserIdDelete = <
  TData = AxiosResponse<void>,
>(
  projectId: string,
  userId: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.delete(
    `http://127.0.0.1:8000/projects/${projectId}/members/${userId}`,
    options,
  );
};
export type ListProjectsProjectsGetResult = AxiosResponse<ProjectResponse[]>;
export type CreateProjectProjectsPostResult = AxiosResponse<ProjectResponse>;
export type ReadProjectProjectsProjectIdGetResult =
  AxiosResponse<ProjectResponse>;
export type UpdateProjectProjectsProjectIdPatchResult =
  AxiosResponse<ProjectResponse>;
export type DeleteProjectProjectsProjectIdDeleteResult = AxiosResponse<void>;
export type AddProjectMemberEndpointProjectsProjectIdMembersPostResult =
  AxiosResponse<ProjectMemberResponse>;
export type ListProjectMembersProjectsProjectIdMembersGetResult = AxiosResponse<
  ProjectMemberResponse[]
>;
export type UpdateProjectMemberRoleProjectsProjectIdMembersUserIdPatchResult =
  AxiosResponse<ProjectMemberResponse>;
export type RemoveProjectMemberProjectsProjectIdMembersUserIdDeleteResult =
  AxiosResponse<void>;
